import re
import sys
import subprocess
import os
import shutil

def extract_chunks(content):
    # Chunk 1: String Table
    # Regex for 'local f={...}' handling escaped strings
    # We look for 'local var={' and capture until the matching '}'
    # Regex explanation:
    # local\s+(?P<var>\w+)\s*=\s*\{   : Matches "local f={"
    # (?: ... )*                      : Non-capturing group for content
    # [^}"\']                         : Any char that is not }, ", or '
    # "(?:[^"\\]|\\.)*"               : Double-quoted string (handles escapes)
    # \'(?:[^'\\]|\\.)*\'             : Single-quoted string (handles escapes)
    # \}                              : Closing brace
    table_pattern = re.compile(r'(local\s+(?P<var>\w+)\s*=\s*\{(?:[^}"\']|"(?:[^"\\]|\\.)*"|\'(?:[^\'\\]|\\.)*\')*\})', re.DOTALL)

    table_match = table_pattern.search(content)
    if not table_match:
        raise ValueError("Could not find String Table (Chunk 1)")

    table_chunk = table_match.group(1)
    table_var = table_match.group('var')
    table_end_pos = table_match.end()

    # Chunk 3 End: Start of VM payload
    # Identified by 'return(function'
    payload_pattern = re.compile(r'return\s*\(\s*function')
    payload_match = payload_pattern.search(content, table_end_pos)

    if not payload_match:
        raise ValueError("Could not find start of VM payload (Chunk 3 end)")

    decryptor_end_pos = payload_match.start()

    # Middle section contains Shuffle (Chunk 2) and Decryptor (Chunk 3)
    middle_section = content[table_end_pos:decryptor_end_pos]

    # Split Shuffle and Decryptor
    # Decryptor block typically starts with 'do local'
    split_pattern = re.compile(r'\bdo\s+local\b')
    split_match = split_pattern.search(middle_section)

    if split_match:
        shuffle_chunk = middle_section[:split_match.start()]
        decryptor_chunk = middle_section[split_match.start():]
    else:
        # Fallback if strict structure isn't found
        print("Warning: 'do local' separator not found. Assuming middle section is entirely Shuffle/Decryptor logic.")
        shuffle_chunk = middle_section
        decryptor_chunk = ""

    return table_var, table_chunk, shuffle_chunk, decryptor_chunk

def generate_lua_harness(table_var, table_chunk, shuffle_chunk, decryptor_chunk):
    lua_code = f"""
-- Generated by extractor.py

-- Chunk 1: The String Table
{table_chunk}

-- Chunk 2: The Shuffle Loop
{shuffle_chunk}

-- Chunk 3: The Decryptor
{decryptor_chunk}

-- 4. Dump the table
local targetTable = {table_var}

print("--- Decrypted Strings Start ---")
if type(targetTable) == 'table' then
    for k, v in pairs(targetTable) do
        print("[" .. tostring(k) .. "] " .. tostring(v))
    end
else
    print("Error: Target variable '" .. "{table_var}" .. "' is not a table.")
end
print("--- Decrypted Strings End ---")
"""
    return lua_code

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 extractor.py <obfuscated_file.lua>")
        sys.exit(1)

    filepath = sys.argv[1]

    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' not found.")
        sys.exit(1)

    try:
        with open(filepath, 'r', encoding='latin1') as f:
            content = f.read()

        table_var, chunk1, chunk2, chunk3 = extract_chunks(content)

        print(f"Detected String Table Variable: {table_var}")

        temp_lua = "temp_decrypt.lua"
        harness_code = generate_lua_harness(table_var, chunk1, chunk2, chunk3)

        with open(temp_lua, 'w', encoding='utf-8') as f:
            f.write(harness_code)

        print(f"Generated harness: {temp_lua}")

        # Check for Lua
        lua_exec = shutil.which("lua") or shutil.which("lua5.1") or shutil.which("luajit")

        if lua_exec:
            print(f"Running with {lua_exec}...")
            result = subprocess.run([lua_exec, temp_lua], capture_output=True)
            print(result.stdout.decode('utf-8', errors='replace'))
            if result.stderr:
                print("Lua Stderr:", result.stderr.decode('utf-8', errors='replace'))
        else:
            print("Error: Lua interpreter not found in PATH.")
            print(f"Please run 'lua {temp_lua}' manually to view the decrypted strings.")

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
